build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "accelerate==0.31.0"
    - "diffusers==0.29.1"
    - "transformers==4.41.2"
    - "torch==2.3.0"